### PR TITLE
Fix: Relay clearing all restrictions and exceptions of the collar upon receiving !release or @clear

### PR DESCRIPTION
**Pull request by KristenMynx**
Many comments regarding this (by me) are in #753.    This fix could potentially also fix: #773, #725, #722.

The relay is changed to send all RLV commands through RLV_CMD link messages so the rlvsys can handle them.  oc_rlvsys then arbitrates between collar restrictions and exceptions and relay restrictions and exceptions.   Previously the relay would send its rlv commands directly to the viewer.

Also removed DO_RLV_REFRESH and changed the way the release functions.

### CODE REVIEW

**Comment by tayaphidoux** [comment]
@KristenMynx it does fix the issue but does not clear the relay set restrictions the solution for this is instead of @clear when its called keep a list in the relay script of the settings requested, and parse through it undoing each one rather than just passing the @clear.

**Comment by tayaphidoux** [comment]
@KristenMynx further study suggests that instead of doing away with DO_RLV_REFRESH hunt down why RLV_REFRESH is not triggering a the default settings to re initialize!

**Comment by tayaphidoux** [comment]
can you explain what removing else if(iNum == TIMEOUT_FIRED)
        {

            if(sStr == "recheck_lock"){
                if(!g_iCollarLocked){
                    llOwnerSay("@detach=y");
                }
            } has to do with it

**Comment by tayaphidoux** [comment]
@KristenMynx found a solution

`
RLV(string cmd,key kID)
{
    if(kID == NULL_KEY || kID == "" ){
        if( Source == NULL_KEY || Source == ""){
            kID == "a94c4e13-ff4f-4686-b14f-877c6424d9d8";
        } else {
            kID == Source;
        }
    }
    // send the rlv command to oc_rlvsys
    llMessageLinked(LINK_THIS, RLV_CMD,
        llGetSubString(cmd,1,999),  // knock off the "@"
        kID);
    //    "a94c4e13-ff4f-4686-b14f-877c6424d9d8");
    // we use a UUID as the source because oc_rlvsys determines
    // if this is an external object or an internal script which sent the RLV_CMD.
    // since we're sending this internally on behalf of an external object we use a UUID
    // eventually we should pass the actual object, so oc_relay can then handle multiple relay objects
    // because oc_rlvsys seems to be able to handle/abritrate/manage multiple sources.
}
`
and every where RLV() is called use Source or the available id in places where source is not yet set.

**Review by tayaphidoux — CHANGES_REQUESTED** [review]
needs just a small change and it will work as intended i proposed the change in the comments we can change it here or submit it and i can make a pull request.

**Comment by KristenMynx** [comment]
@tayaphidoux   Regarding 'why RLV_REFRESH is not triggering a the default settings to re initialize!'   RLV_REFRESH is not supposed to do that.  The purpose of RLV_REFRESH is to inform all plugins/addons that they should reinstate their RLV state (through RLV_CMD) because something happened (login, rez, reset).   It is not a command to rlvsys to refresh the state of things.   rlvsys does that automatically upon startup.   RLV_REFRESH should not cause the default settings to reinitialize.

It is the responsibility of each plugin/addon to watch for *SETTING* link messages and set their internal variables.   Settings are pulled when rlvsys startes up, so all plugins should get their settings as a side effect of rlvsys pulling.    No plugin should need to as for settings on their own.  

The same applies to RLV_VERSION and RLVA_VERSION.   rlvsys informs every plugin/addon through those link messages of the rlv version(s).  It does this on every startup (wear/rez/reset/inventory change).   There should never be a need for a plugin to ask for that information, simply notice the messages and store the result as it needs.

**Comment by KristenMynx** [comment]
All that said, in my view, the changes as offered need testing.

**Comment by corvannansen** [comment]
My girl and I encountered this error with the "CLEAR ALL" command in the RLV menu. The fix worked, and exceptions were not cleared when other restrictions were.

**Review by tayaphidoux — APPROVED** [review]
still would like to see changes added but if they aren't that can be solved later, we have had a regular user prove that the changes do solve the problems expressed.

**Comment by KristenMynx** [comment]
@tayaphidoux  I totally agree that your idea should work.   I'm simply taking a conservative approach of not releasing a new feature (handle multiple devices) at the same time of a philosophical change in the way that rlv calls and rlv state are being handled by the relay.

**Comment by tayaphidoux** [comment]
@KristenMynx 
1) without the change your code falls short of working.
2) its already got the filter to prevent more than one device operating at the.
3) this is in no way trying add the new feature but fix a bug.

**Comment by KristenMynx** [comment]
@tayaphidoux Can you clarify the change you'd like then.   I'm totally missing something then.

**Comment by KristenMynx** [comment]
@tayaphidoux Ok i see it is not a feature add.   I do fail to see how it falls short of working.  

Sending Source through instead of a constant UUID seems safer.   oc_rlvsys will see a the relay as a single entity, regardless of what devices appear and disappar throughout the course of the relays use over time.    That seemed safer to me, until we can code the relay be multi-device.

**Comment by tayaphidoux** [comment]
@KristenMynx  i have said this four times now.
when an object engages with relay it works correctly, when you end engagement in the case of the muffin milkers  which i tested on it does not release the restrictions, none at all what so ever, which prevents it from clearing collar restrictions but breaks the relay's functionality.

**Comment by KristenMynx** [comment]
@tayaphidoux Thank you!

**Comment by KristenMynx** [comment]
@tayaphidoux I have heard of the concept, but have no experience.

**Comment by tayaphidoux** [comment]
@KristenMynx  they apply the following restrictions through the relay

### RLV RESTRICTIONS #####################
### TE - Paws Collar Safra's Pony - chest - test (Neck) #####################
-------- unsit
-------- tploc
-------- tplure_sec
-------- showworldmap
-------- showminimap
##########################################

**Comment by SilkieSabra** [comment]
I see there is an approving review but there are two coders in this conversation and both of you have contributed code to the same pull as far as i can tell.  Can we get an inworld script you both agree on that can be tested?  I think this could be the last piece we need to push an update that will support the AO and Cuffs.

**Comment by KristenMynx** [comment]
@SilkieSabra I did a bunch of testing with the script is pulled from the net result of my pull request on the device that @tayaphidoux  tested on.    We worked together, but I was unable to make it fail.   One possibility was that she's using ask mode.   So I came back today to test with ask mode.    Things worked properly in a sense, but I found a new bug in ask mode.   In ask mode, only the first restriction is accepted, all others are ignored.   I found a fix for this bug and will be doing another change to my pull request to fix that.    I discovered yet another bug... The relay tries to remember a source that was granted access (the last 5 since rez/wear) and not bother to prompt again.   This doesn't appear to work.  If its an easy to fix and low risk change I'll do that too.

**Comment by KristenMynx** [comment]
@tayaphidoux @SilkieSabra   I've sent you oc_rlvsys PR 794 and oc_relay PR 794 in world.
Testing should be done for the original bug, plus Phidoux's issue: when a device releases you, not all those restrictions are removed.    Also test if Ask mode adds (during capture0 and removes (during release) all the restrictions that the device requested.

**Comment by tayaphidoux** [comment]
@KristenMynx  i will have to try it when i next get on that would be the optimal time, one other reason i may not work  for me is i am using kokua which is RLV not RLVA but that don't explain why getting the key from the object works where your key does not, however i will give your scripts a try

**Comment by tayaphidoux** [comment]
@KristenMynx had an issue where i had to re log because the relay kept the last item to ask for relay permission when i got off it enough time didn't pass for the new item to be able to request permission, i am testing weather it releases on its own today

**Review by JennGoodman — APPROVED** [review]
[Kitty(sweetdangerkitty) ]The code is good. Just need to resolve the merge conflict.

**Review by Pingout — APPROVED** [review]
Relay and RLVsys both working well

**Pull request merged**
