### PR TITLE
oc_addon_standalone_template

### PR DESCRIPTION
**Pull request by tayaphidoux**
adding the oc_addon_standalone_template

this template capitalizes on changes i have made to the ao that allow it to be a stand alone addon, and connect and stay connected to the collar more reliably.

This Template is designed to be used in projects of harnesses, cuffs, gags, chastity belts, boots, etc.
worn items furnature addons can use the other template where as the items in the categories above need somthing alot more stable and reliable, this template makes it so that the addon can function even when the collar is not connected,
it gets it's authentication list from the collar by default, but its not to hard to write a menu to add owners/trusted to the list, it may take a bit of modification to prevent collar from overwriting it either way you can click or use /1[prefix]addonname to bring up menues or input commands.

this addon has 3 states
default = boot where it tests if a collar can be connected to, or if in offline mode it just goes strait to 
state offline = no connection to collar and the script acts like it would if never was made to.
state online = connection to the collar where every thing except touch interaction is passed through the collar.

it includes the admin menu i made for the ao that provides a way to reset the ao and for addons it can print out stored
linkset data information for debugging while building, the clearing/resetting of the ao has a confirmation menu which is designed so that it can be used for other confirmation type questions.

one of the needs for offline mode is so that the item does not get stuck with no way to connect it if it fails to connect on login/sim crossing, it also allows the owner to utilize it incase you wish to lock out the submissive. 

clearing LSD with llLinksetDataReset() forces all scripts to call llResetScript() which prevents scripts holding onto out dated information.

safeword will cause the addon when connected to the collar to do LSD reset if it is in offline mode when you safe word it will not do a thing to change its configuration however it will update owners list and perfix on.

https://www.merriam-webster.com/dictionary/stand-alone
a : intended, designed, or able to be used or to function alone or separately : not connected to or requiring connection to something else in order to be used or to function

"Run on kerosene or diesel, stand-alone cabin heaters operate without electricity …"—
Skip Novak

especially : operating or capable of operating independently of other software or hardware

"Amazon, for example, wants to offer the app as a channel in its Prime Video suite, rather than a standalone app next to Prime. Doing so gives Amazon access to data such as watching habits and preferences." —
Kim Khan

"The market has seen a number of more capable VR headsets hit shelves, the most recent being the standalone Oculus Quest, which doesn't require a PC like the Oculus Rift". —
Brittany A. Roston

### CODE REVIEW

**Comment by tayaphidoux** [comment]
https://github.com/OpenCollarTeam/OpenCollar/pull/960/commits/7ed0a4b443bdec3517e2a99b73bb49b56569eaab - updated commented information about the update.

**Comment by tayaphidoux** [comment]
fixed syntax and naming errors

**Comment by Yosty7B3** [comment]
How is authorization suppose to work?
It seems that it will remember the collar owners even if the collar is removed of if the owner list is cleared in the collar.
Is that intentional?


suggestion:

* I would like to see the menu script send out a MENUNAME_REQUEST and accept MENUNAME_RESPONSE to add buttons without having to edit the script.
That way the scripts can work as is without having to do any editing on them.

* Maybe have the option in the  Admin menu to set the addon_name

**Comment by tayaphidoux** [comment]
@Yosty7B3  interesting ideas, as for the owner list yes it will remember owners after collar is cleared if collar and addon are not connected, it should replace the owner menu if the collar is connected, it acts on updates to auth_owner and auth_trust updates in settings chatter to the addon, i do plan on adding a mode where its offline i.e. not connected to the collar to manage owners, and possibly run away, just in case.

**Comment by Yosty7B3** [comment]
@tayaphidoux Ok yes that makes sense. 
But when trying it, it doesn't update the owner/trust list when the list received from the collar is empty.
I tried looking where the problem lies and seems to be these lines:

`                                if(sVal != "" && sVal != llLinksetDataRead("auth_owner"))`
and
`                                if(sVal != "" && sVal != llLinksetDataRead("auth_trust"))`
which expect an empty sVal to pass.

**Comment by tayaphidoux** [comment]
@Yosty7B3  ah i see where i goofed should be an easy fix i will get to it after i get my morning choores done.

**Comment by Yosty7B3** [comment]
Ok, digged some more into it and got some more feedback. Hope that's ok :)

Having the LSD token names dependent on g_sAddon seems unnecessary. 
Since there only ever is going to be one addon per object, can just as well use "addon" as pre-token
example: `llToLower(g_sAddon)+"_listen"` could just be `"addon_listen"`
The way it is now, he first time someone puts the script in, it'll start with an empty g_sAddon so settings are getting set without a pre-token at all.
Then when they change g_sAddon to the actual name, a second set of setting will be written.
I know the old ones can easily be removed with a LSD reset, but I believe it adds unnecessary complication, and it'll make it easier for any future code if the token names are predetermined instead of dependent on g_sAddon.

**Comment by tayaphidoux** [comment]
@Yosty7B3  
You are right about using addon instead of g_saddon, as for it being blank this is template for builders i did have an idea for g_saddon to be populated with the object name if it was blank buti forgot to impliment it, and i epxpect people to change it any ways, i have the reset built into the admin menu for issues with the addon that could cause ti to stop functioning correctly or to refresh the settings if the user/owner wishes to do that, for me currently it helps with the problem you described when i change a setting key token.

**Comment by tayaphidoux** [comment]
i may close this one soon and redo it as the changes i have made to include a menu where you can add buttons has reduced the script number and comleatly changed the stand alone setup quite a bit.

**Comment by tayaphidoux** [comment]
updated the standalone_addon_template to include suggestions from @Yosty7B3  dunno if its quite what they were thinking and it also improves uppon what the ao has setup.

**Comment by tayaphidoux** [comment]
i just realized i forgot one option and thats the group setting i need to figure out hwo best to handle that key from the menu, right now it is supplied form the collar when in addon mode.

**Comment by Pingout** [comment]
I'm not sure how to test this. 
The thing is..... this is a template for an addon, so by definition it's not a complete addon. 
So i would need to add some code into the template to make it do what i want my addon to do. Lets say I want to make a Muzzle Addon. I would need to point at a garble script, or maybe add the garble instructions into this template. I have no clue where or how to do that. I get the idea of the script, having a stand-alone access list but still compatible with OpenCollar Addons. I just don't know how to correctly add my instructions to this template.

**Comment by tayaphidoux** [comment]
@Pingout 

FROM oc_addon_auth.lsl
this Facilitates the communication to oc_addon_menu.lsl via integer DIALOG
```
integer DIALOG                  = -9000;
integer DIALOG_RESPONSE         = -9001;
//integer DIALOG_TIMEOUT         = -9002;
integer MENU_REQUEST            = -9003;
integer MENU_REGISTER           = -9004;
integer MENU_REMOVE             = -9005;
integer MENU_RESPONCE           = -9006;

Dialog(key kID, string sPrompt, list lButtons, list lUtilityButtons, integer iAuth, string sName)
{
    llMessageLinked( LINK_SET, DIALOG, sPrompt+"^"+llDumpList2String(lButtons,"`")+"^"+llDumpList2String(lUtilityButtons,"`")+"^"+(string)iAuth+"^"+sName, kID);
}
```
This facilitates responce of buttons pressed in menu.
```
    link_message(integer iLink, integer iNum, string sMsg, key kID)
    {
        if(iNum == DIALOG_RESPONSE)
        {
            list lPar = llParseString2List(sMsg,[","],[]);
            integer iAuth = llList2Integer(lPar,0);
            string sMenu = llList2String(lPar,1);
            sMsg = llList2String(lPar,2);
            integer iRespring = TRUE;
            if (sMenu == "Auth~Main")
            {
```
this is used to add buttons to oc_addon_menu.lsl
`llMessageLinked( LINK_SET, MENU_REGISTER, g_sPlugin, "");`

this calls the menu of the script in whichthe menu resides you only need to add the menus you expect to be called
form command or another script here


```
        else if(iNum == MENU_REQUEST)
        {
            list lPar = llParseString2List(sMsg,["|"],[]);
            integer iAuth = llList2Integer(lPar,0);
            string sMenu = llList2String(lPar,1);
            if(sMenu == "Access")
            {
                Menu( kID, iAuth);
            }
        }
```
this is an example of a menu structure that display dialog box with auth_noaccess token blocking the user.
buttons that are toggle use b_sName or b(utton)_(string)Name with a simple boolean flipflop that came from the old ao.
```
Menu(key kID, integer iAuth)
{
    b_sGroup = llList2String(g_lCheckBoxes,(llLinksetDataRead("global_group")!=NULL_KEY))+"Group";
    string sPrompt =    "|=====Main=====|";
    list lButtons   = ["-"];
    if(iAuth == CMD_WEARER && (integer)llLinksetDataRead("addon_noaccess"))
    {
        sPrompt += "!!!NOT AUTHORIZED!!!";
        lButtons = ["-"];
    }
    else
    {
        lButtons = ["+Owners","+Trusted","+Blocked","-Owners","-Trusted","-Blocked",b_sGroup,"Access List"];
    }
    list lUtilityButtons = [UPMENU];
    Dialog(kID, sPrompt, lButtons, lUtilityButtons, iAuth, "Auth~Main");
}
```
FROM oc_standalone_addon_template.lsl
this is how you create a chat command call
```

    else
    {
        list lCommands  = llParseString2List ( sStr, [ " " ], [ g_sAddon, llToLower ( g_sAddon ) ] );
        string sToken   = llToLower ( llList2String ( lCommands, 1 ) );
        string sValue   = llList2String( lCommands, 2 );
        llLinksetDataWrite ( "menu_user", (string) kID );
        if( sToken == "lock")
        {
            llSay(0,"The lock clicks as secondlife:///app/agent/"+(string)kID+"/about locks it!");
            llLinksetDataWrite("addon_lock",(string)TRUE);
        }
```

**Comment by tayaphidoux** [comment]
@ping yes you modify menu and standalone_addon_template or you can create a menu/app that ties in using dialog and dialog_response, as welll as menu_register,menu_request,menu_responce, via link message, the auth script is an examlpe of how to add function without changing the two core items.

**Comment by tayaphidoux** [comment]
updated the scripts with comments to hopefully help paint the picutre of what the scripts are doing and how they are doing it, i also added linkmessage chatter relay for chat commands and collar so that users don't even have to modify the stand alone scripts to build a project just just add an app and buttons to main menu.

**Comment by tayaphidoux** [comment]
i will be working on a smaller example for the button and relay system since auth may be daunting to new creators.

**Comment by Yosty7B3** [comment]
For handling menu buttons you chosen to use different link messages then we are used to in the main collar scripts.
I think that for clarity and compatibility it would be better to keep them consistent.
It would be nice if one could just put in for example the leash script and it would just work (or with minimum editing) because of using compatible protocols.

Yours:
```
integer MENU_REQUEST            = -9003; // Request a menu from another script.
integer MENU_REGISTER           = -9004; // Register a button to Main menu.
integer MENU_REMOVE             = -9005; // Remove a button from Main menu.
integer MENU_RESPONCE           = -9006; // Responce from Registration or Removal of button.
```

Collar:
```
integer MENUNAME_REQUEST = 3000;
integer MENUNAME_RESPONSE = 3001;
integer MENUNAME_REMOVE = 3003;
```


MENU_REGISTER  has the same function as MENUNAME_RESPONSE (it adds a button), yet uses a different value then we are used to in collar scripts.
Same for MENU_REMOVE, which does the function of MENUNAME_REMOVE, but again had a different value



On line 406 in oc_addon_menu you use the completely new link message MENU_REQUEST:
`llMessageLinked( LINK_SET, MENU_REQUEST, (string)iAuth+"|"+sMsg, kID);`

while collar compatible that would be:
`llMessageLinked(LINK_SET, iAuth, "menu "+sMsg, kID);`
													
So the introduction of MENU_REQUEST seems unnecessary, when the previous collar method would work just as fine.

The name MENUNAME_REQUEST is used in collar scripts to request other scripts to sent their menu button, which makes the name MENU_REQUEST confusing as it's almost the same name but different function. 
You use LSD "addon_ready" to tell scripts when it's time to send their buttons, which is fine. But I do think it would be good to also still send the original MENU_REQUEST, again to stay compatible with existing scripts.

MENU_RESPONCE, which you use to report back if the button has a valid name seems a bit unnecessary to me (and again the naming of it is confusing with MENUNAME_RESPONSE ). If a button used improper names, then just don't add it to the menu. No need to send a dialog message for it.

**Comment by tayaphidoux** [comment]
@Yosty7B3  first of all i don't know how the collar menu does it to do so would require i take and modify the script to be readable which takes a long time and tiring amount of keyboard work, next i would do it that if i did fully understand it this menu i wrote from scratch taking what i learned from what the AO had when i started, as for the link names MENUNAME_REQUEST and  MENU_REQUEST is not confusing to me MENUNAME_REQUEST sounds like you are asking for the script to register a button.

MENU_REQUEST sounds to me like asking the menu to generate a menu, MENUNAME_REQUEST and MENU_REGISTER are similar based on what  you describe and as above they are different for that reason, MENU_REGISTER is the script announcing buttons to be added to the main menu so the name in my mind works since its not the menu script asking the other script what menus it wants but a prompt from the third party script telling the menu what button it uses, same idea different perspective.

as for MENU_RESPONCE it tells the third party script which as you pointed out gives feed back on menu registration the menu registration response is for debugging purposes, some times its helpful to get feed back if you aren't willing to dig into a script to figure out how it works which plays to its name MENU_RESPONSE a channel to feed back information from one of the other items.

**Comment by SilkieSabra** [comment]
I feel like I must leave a comment here about the entire pr process.  I love to see you, Phidoux, doing so much creative effort, and I love to see Yosty working with you to refine it.  This all should have been done before making a pr.  When you make a pr, you are asking us to merge your code into the OpenCollar repository.  At the very least, pull requests should conform to the existing OpenCollar style base and overall design.  If you are working up an idea for a new feature, it needs to be approved in concept before making the pr. See [https://opencollar.cc/docs/Development-Life-Cycle](https://opencollar.cc/docs/Development-Life-Cycle) for more on proposing new features.   Please don't offer us unfinished or untested designs via the pr process.  This is to avoid unnecessary work and backtracking down the line, for all of us, including most of all the person with the idea.  I haven't seen any formal specs for your template, and defining "stand-alone" for us doesn't suffice.  Instead, I see your concept changing as you make, withdraw and repost dozens of prs.  We are trying not to leave prs hanging for so long these days but your way of working with them makes that much more difficult.

**Comment by tayaphidoux** [comment]
@SilkieSabra  alright i get the message

**Pull request closed without merging**
