### PR TITLE
Update oc_rlvsys.lsl

### PR DESCRIPTION
**Pull request by Medea-Destiny**
Fix for issue #842

### CODE REVIEW

**Comment by Medea-Destiny** [comment]
Testing required:

Proper handling of collar lock when being grabbed and released via the relay. Ensure that this does not leave an unlocked collar locked, or a locked collar unlocked, and that the checkbox in the main menu for the collar lock continues to correspond to actual status. Thus it should be ticked when the collar is locked, and unticked when the collar is unlocked, but also unticked if the collar is unlocked by an @detach=n has been issued due to relay restrictions.

**Comment by pfifo** [comment]
It seems that a locked collar will remain locked when RLV is turned off and g_lBaked does NOT contain 'detach' which seems to be possible IF the code added on line 281 is triggered, because g_lBaked is not updated along with the llOwnerSay("@detatch=n") that is called.
It may be better to call ApplyAdd("detach") instead of calling llOwnerSay() directly.

**Comment by Medea-Destiny** [comment]
@pfifo Good spot -- a slightly different issue, but indeed if RLV is turned off while the relay has active restraints (including detach) this would have the impact of unlocking the collar. Easy enough fix!

**Comment by Medea-Destiny** [comment]
Have updated the code in question as follows:

```
        integer relockcheck;
        if(llListFindList(g_lBaked,["detach"])!=-1) relockcheck=TRUE;
        while (llGetListLength(g_lBaked)){
            llOwnerSay("@"+llList2String(g_lBaked,-1)+"=y"); //remove restriction
            g_lBaked=llDeleteSubList(g_lBaked,-1,-1);
        }
        if(relockcheck==TRUE && g_iCollarLocked==TRUE) llOwnerSay("@detach=n");
```
... so that we check the baked list for a detach, and restore the @detach=n if it is found and the collar is locked.

As for unlocking the collar if RLV is switched off -- as far as I have always understood, the RLV off function should be considered relating to functions in the RLV menu, not necessarily all RLV functions, so the collar shouldn't be unlocked by it. However if anyone has differing opinions (@SilkieSabra ?) speak up!

**Comment by Pingout** [comment]
I tried to devise a test for this change, but i was somewhat confused as to the expected behavior.
First, we have spent a week, using various test situations, to check the collar lock/unlock statud checkbox. We tried teleporting, surviving a crash, surviving a sim restart etcetra. The checkbox remained in a correct status, whether locked or unlocked.
Second, I set up a BDSM device, using AV Sitter scripting which allows a command to set restrictions for the submissive on capture. Here's part of the AVpos notecard:
     RLV 1
     ROLES S
     ONTOUCH ASK
     ONSIT CAPTURE
     TIMELOCK 2
     RECAPTURE 1
     ONCAPTURE @detach=y
Using the previous oc_rlvsys script i was able to make the collar detachable even though the Lock checkbox was still in a Locked state.  With the newest script (https://github.com/OpenCollarTeam/OpenCollar/compare/Medea-Destiny-patch-3) the furniture was no longer able to defeat the collar's @detach=n
I think this means the test was successful, but i will leave it to @Medea-Destiny and @SilkieSabra to decide

**Comment by SilkieSabra** [comment]
I agree that turning RLV off in the collar should not unlock the collar.  Good spot.

**Comment by Pingout** [comment]
> Thus it should be ticked when the collar is locked, and unticked when the collar is unlocked, but also unticked if the collar is unlocked by an @Detach=n has been issued due to relay restrictions.

The collar lock works irrespective of RLV status

**Comment by Medea-Destiny** [comment]
@Pingout Thanks for the thorough testing! Yes this is as expected and we're good to merge. :)

**Pull request merged**
