### PR TITLE
Nikki lacrima patch runaway

### PR DESCRIPTION
**Pull request by NikkiLacrima**

### CODE REVIEW

**Comment by NikkiLacrima** [comment]
Updated runaway handling as discussed in issue #1001 
Also removed g_lMenuIDs in these files see #963

**Review by Pingout — APPROVED** [review]
Received (4) script from Nikki
    oc_api
    oc_core
    oc_leash
    oc_relay

After installation, the [prefix] runaway command will bring up a menu for the Wearer
 "Are you sure you want to runaway from all owners?"
and offers a Yes, No, and Disable option

For the Owner, the [prefix] runaway command will bring up a menu offering the
option to Disable 

When the Owner selects the Disable button, the collar Wearer gets an Accept/Deny
option. Once accepted by the Wearer, the setting "auth=runaway~0" is in place and
a further [prefix] runaway from the Wearer results in a notice to the wearer:
 "Access Denied to runaway, or the runaway settings menu"
If the collar owner uses the [prefix] runaway command again, they get a menu with 
the option to Enable runaway

Conclusions: The fix works as expected. Thank you.

**Comment by Medea-Destiny** [comment]
Some preliminary notes:

oc_api line 725, notify owners is sent after owner list is deleted. This line should go above the LM_SETTING_DELETE lines, and it may not be a bad idea to drop in an llSleep(0.5); in case of message timing funkiness.

oc_leash line 488 triggers Unleash function on runaway_confirmed. This function provides notification of who's unleashing what, then triggers the DoUnleash function.  However we also have CMD_SAFEWORD trigger DoUnleash on line 757. I don't think we need the specific unleashing text when a runaway is performed, and the runaway triggers CMD_SAFEWORD, so I don't think we need the runaway_confirmed handling in the UserCommand functioning at 488, and that saves the double call to DoUnleash.

Credits at the top of oc_leash have no detail of changes, and I think all 3 scripts could use a mention of "implemented Yosty's menu streamlining".

Will take a deeper dive soon. Thanks so much for handling this, @NikkiLacrima !

**Comment by NikkiLacrima** [comment]
Medeas comments fixed. Time to merge ?

**Review by Pingout — APPROVED** [review]
As a double check, I brought these three updated scripts inworld, and they all tested the same as the last time.

**Pull request merged**
