### PR TITLE
Update oc_undress.lsl

### PR DESCRIPTION
**Pull request by Medea-Destiny**
Extended layer handling and chat commands added

### CODE REVIEW

**Comment by Medea-Destiny** [comment]
This addresses #528 and adds chat commands to undress. I have done initial testing on Firestorm and it all seems good. However due to the inconsistencies in behaviour between RLV and RLVa this really should be testing on a different viewer that uses Marine's RLV implementation before merging

**Review by SilkieSabra — COMMENTED** [review]
This makes sense to me.  Let's test.

**Comment by Pingout** [comment]
Everything tested good. Works as expected.

**Comment by Trinkitz** [comment]
We tested this with tattoo and clothing layers on a Maitreya mesh body. No problems; clothing lock also worked fine. We also removed the Maitreya body alpha using undress.

**Pull request merged**
