### PR TITLE
Poses reorganized

### PR DESCRIPTION
**Pull request by tenshilove**
created flat-footed and high heel versions of the poses and sorted each to different folders

### CODE REVIEW

**Comment by zontreck** [comment]
Please refrain from closing the pull request only to reopen a new one. It makes it harder to review changes, please just push changes to the branch for the pull request

**Comment by tenshilove** [comment]
> Please refrain from closing the pull request only to reopen a new one. It makes it harder to review changes, please just push changes to the branch for the pull request

Will do from this point forward, having said so the previous pull was closed because the folder name changed.

**Comment by zontreck** [comment]
well if you change a folder name just make a new commit. The pull request will automatically add the new commit :)

**Comment by tenshilove** [comment]
deal :) Still figuring out these pulls and pushes, i hope i get them right next time *blush*

**Comment by zontreck** [comment]
This will be reviewed later today.

**Comment by zontreck** [comment]
Why was this closed?

**Pull request closed without merging**
