### PR TITLE
fix v7.1 script errors, add "face=n" and/or "specular=xxx" and/or "normal=yyy" in .themes

### PR DESCRIPTION
**Pull request by RestlessSwords**
1) 7.1 oc_themes changed lines 454-454, line 453 was incorrect, causing errors on texture/color changes
```
                                    list lPrimParams = llGetLinkPrimitiveParams(iLinkCount, [PRIM_TEXTURE, iFace ]);
                                    lPrimParams = llDeleteSubList(lPrimParams,0,0); // get texture params
                                    llSetLinkPrimitiveParamsFast(iLinkCount, [PRIM_TEXTURE, iFace, 
```
2) added some lines so .themes now supports OPTIONAL "face=n" in .themes notecards
example:
```
[ White+Red ]
Band~TextureWhite~<0.99, 0.99, 0.99>
Band~face=3~TextureRed~<0.99, 0.99, 0.99>
[ Red ]
Band~TextureRed~<0.99, 0.99, 0.99>
```

### CODE REVIEW

**Comment by nirea** [comment]
The path for this file should be `src/collar/oc_themes.lsl`.  Can you push a new commit to your branch with the file moved to that location?  Then Github will show a useful diff and the file will be put in the right place when/if I click "Merge".

**Comment by RestlessSwords** [comment]
new commit pushed to:  OpenCollar-1/src/collar/oc_themes.lsl

**Comment by Medea-Destiny** [comment]
While I stand by my suggestions in the issues thread that there are more flexible ways to do this, what we have here looks good to go. Fixes a standing bug and brings in new features. Let's have this in 7.2. Thank you, Restless.

**Comment by zontreck** [comment]
The file is still in the wrong path on this branch.

**Pull request merged**
