### PR TITLE
fix camdist 0 bug

### PR DESCRIPTION
**Pull request by tayaphidoux**
this should fix a bug on viewers that kick you out of mouse look on teleport or sim crossing.

### CODE REVIEW

**Comment by tayaphidoux** [comment]
https://github.com/OpenCollarTeam/OpenCollar/issues/778 - i describe the issue this code fixes here.

**Comment by Medea-Destiny** [comment]
@tayaphidoux The code seems fine here, however I'm still not clear this is a bug we actually _should_ be making a workaround for. As I understand it's something that so far has only been reported with Singularity? Shouldn't this then be reported on the Singularity JIRA for them to fix?

**Comment by tayaphidoux** [comment]
@Medea-Destiny then try it out for your self put your self in forced mouse look and try to teleport, on a viewer other than firestorm,just because firestorm likes to violate the shared experience by being the only viewer to not properly engage mouse look based on distance from avatar, does not mean that its not a bug that you can't turn and move when your camera is locked into mouse look like it should be.

**Review by KristenMynx — APPROVED** [review]
The changes look fine.   I don't see any harm sending a couple more viewer messages on region change.  Yes it probably should be a viewer fix, not an OC fix, but it doesn't look expensive to me.

**Comment by tayaphidoux** [comment]
its a work around i am not blaming oc for causing it its a miss comparability between rlv calls and viewers default functionality as defined by linden labs, so most viewers will comply unless they actually test the features to ensure compatibility, in the mean time this was what i came up with.

> The changes look fine. I don't see any harm sending a couple more viewer messages on region change. Yes it probably should be a viewer fix, not an OC fix, but it doesn't look expensive to me.

**Comment by tayaphidoux** [comment]
@KristenMynx should i point this towards q1?

**Comment by KristenMynx** [comment]
2022-q1-features yes.  Also lets see if there are any more comments before merging.

**Comment by tayaphidoux** [comment]
i guess its a good thing this is not merged yet as there appears to be a bug created with this, its not maintaining mouse look on login with my fix.

**Comment by tayaphidoux** [comment]
i am closing this for now because this causes an issue with mouse look and i need to figure out why

**Pull request closed without merging**
