### PR TITLE
changes for more owners in the owner list

### PR DESCRIPTION
**Pull request by pixelwork**
as discussed in https://github.com/OpenCollarTeam/OpenCollar/issues/70 i have merged some changes for more owners to my fork from https://github.com/WendyStarfall/opencollar/blob/master/src/collar/oc_auth.lsl

it shows how many percent of the maximum combined owners+trust+blocklist you already used.

 it also implements a change how self-owned works and makes it a mode of its own instead of just adding yourself to the owner list.

bonus, it optionally re-enables the authorizer prim as LED as it was before

### CODE REVIEW

**Comment by nirea** [comment]
Thank you for submitting this!  If @SatomiAhn is going to submit a pull request implementing https://github.com/OpenCollarTeam/OpenCollar/issues/74, I think I would prefer that direction, as it has the potential to simplify lots of things.

Keeping this open for now though.  If no one steps up to do that implementation, we can go with this easier solution.

**Comment by GarvinTwine** [comment]
Interesting that you claim what we did here: https://github.com/WendyStarfall/opencollar/commit/ebc24b14bb9ea54a8d5c03a149b14a82e4e1cb01 6 days ago to be your work 5 days later...

**Comment by pixelwork** [comment]
dont spread lies otto, nobody here claims this to be solely our work! if you read carefully you would see that the wording "merged" is used

**Comment by GarvinTwine** [comment]
You seem to have a very big misunderstanding between GPL 2.0 and Public Domain my friend.

Of course you can merge GPL code but it has to have matching attributions to who made what changes and your wording "i merged some changes" does attribute only yourself and nobody and nothing else.
What you do here is stealing the commit and attribution.
When this gets merged you are credited to have changed these lines in github for this repository and the ones who actually did this are not even mentioned.

Not solely your work? 
Where is your part of the work here besides copy/pasting our work into here?
None of this is your work!
And in no word any attribution to the ones who made the actual changes or even a hint to where you got it from!

**Comment by pixelwork** [comment]
i actually used the automatic merge function and solved the evolving merging conflicts, to merge changes from https://github.com/WendyStarfall/opencollar/blob/master/src/collar/oc_auth.lsl by "git pull"

credits for all the things are mentioned globally as it has been discussed earlier.

**Comment by nirea** [comment]
All that the GPL requires is preserving the copyright notice.  Wendy and Garvin, your names are still in the copyright notice in the file at issue in this pull request.  That *is* how one "properly attributes" authorship under the GPL.  The GPL says nothing about needing to add extra attributions in commit messages, code comments, or whatever else you're thinking of.  Any claims of theft here are baseless.  

> I choose when, and how, I want to publish my own work.

That's not how open source works.  The whole point is that you're giving the world permission to modify and republish your work.

Further comments about the technical merits of merging this code are welcome here.  More arguing about theft is not.

**Comment by GarvinTwine** [comment]
Just to clarify things here technically:
This is not just about GPL but also about common sense behaviour and attitude on github.
To not just take others work and commit it without naming the ones who did the work in the commit itself.

Funny that you suddenly point to 
>All that the GPL requires is preserving the copyright notice. 

Which was the first thing @nirea took off of all scripts!

Secondly the part where @WendyStarfall  said
>"I choose when, and how, I want to publish my own work."

Is where @pixelwork  **published** a script he did **not** _republish_ but took the script from SL and published it as if it was his on github again without any mention of the author in his commit but added bad words and slander to his commit about some weird made up hiding (a script that gets distributed free and open in every update in SL!).
>which they still decide to hide for security by obscurity... security by obscurity is always a bad bad bad idea and a proof somebody does things he has no clue at all about...

So please keep your comments technical and do not call everything devilish and avoid slandering the works of those you take to work with just because you do not understand everything (maybe you cannot understand because you just were not there when decisions were made for reasons you lack to know), neither in commit messages nor in issues. 
Thank you very much.

**Comment by pixelwork** [comment]
do you know what the term "digitally distributed in machine readable form" means?

once you publish something in digitally machine readable form under a certain license, no matter where you have chosen to distribute it / it has been distributed in that moment and can be used/republished under the terms of that license, and the license used there did allow that.

**Comment by pixelwork** [comment]
I think we can close this pull request now after you merged a little modified version of it.

**Pull request closed without merging**
