### PR TITLE
OpenCollar 8.0 Core Changes

### PR DESCRIPTION
**Pull request by zontreck**
This pull request will be used to track changes to OC 8.0 without affecting the main repository until the new code is stable.

Thus far this includes combining oc_auth, oc_com, and oc_sys into a single script, the new Link Message layer has not yet been added.

### CODE REVIEW

**Comment by zontreck** [comment]
Resolves #337

**Comment by zontreck** [comment]
Resolves #313

**Comment by zontreck** [comment]
Resolves #331

**Comment by zontreck** [comment]
Resolves #128 by implementing a submenu : Addons, this is a place where attachments can hook into the collar, not to be confused with Plugins, aka Apps.

**Comment by zontreck** [comment]
Special thanks to @Yosty7B3 in PR #357 for pointing out the leash script was being hardcoded as a menu button and that it should be sending its menu on the MENUNAME_RESPONSE like everything else.

**Comment by zontreck** [comment]
v8.0 versioning scheme will work something like this:

```
Major.Minor.{Build,RC#,Beta#,Alpha#}
ex: 8.0.0100 would be revision 0, RC1 of v8.0
```

**Comment by zontreck** [comment]
Commit Alpha 1

**Comment by zontreck** [comment]
Committing alpha 1 now

**Comment by Vigdis-SL** [comment]
### V8.0 Alpha1: I cannot change the group. it is perm locked
[20:56:26] NorthernCollar: RLV disabled.
[20:56:26] NorthernCollar V8.0:  executes: @recvim:bda8a4ab-814d-40e8-b2e7-5dfcc2877888=rem
[20:56:26] NorthernCollar V8.0:  executes: @recvim:e1c86e93-b430-435d-bd1c-2f9c2dd73eeb=rem
[20:56:26] NorthernCollar V8.0:  executes: @recvchat:bda8a4ab-814d-40e8-b2e7-5dfcc2877888=rem
[20:56:26] NorthernCollar V8.0:  executes: @recvchat:e1c86e93-b430-435d-bd1c-2f9c2dd73eeb=rem
[20:56:26] NorthernCollar V8.0:  executes: @recvemote:bda8a4ab-814d-40e8-b2e7-5dfcc2877888=rem
[20:56:26] NorthernCollar V8.0:  executes: @recvemote:e1c86e93-b430-435d-bd1c-2f9c2dd73eeb=rem
[20:56:26] NorthernCollar V8.0:  executes: @tplure:bda8a4ab-814d-40e8-b2e7-5dfcc2877888=rem
[20:56:26] NorthernCollar V8.0:  executes: @tplure:e1c86e93-b430-435d-bd1c-2f9c2dd73eeb=rem
[20:56:26] NorthernCollar V8.0:  executes: @accepttp:bda8a4ab-814d-40e8-b2e7-5dfcc2877888=rem
[20:56:26] NorthernCollar V8.0:  executes: @accepttp:e1c86e93-b430-435d-bd1c-2f9c2dd73eeb=rem
[20:56:26] NorthernCollar V8.0:  executes: @startim:bda8a4ab-814d-40e8-b2e7-5dfcc2877888=rem
[20:56:26] NorthernCollar V8.0:  executes: @startim:e1c86e93-b430-435d-bd1c-2f9c2dd73eeb=rem
[20:56:28] NorthernCollar V8.0:  executes: @setgroup:00000000-0000-0000-0000-000000000000=force,setgroup=n (duplicate)

RestrainedLove viewer v3.2.1 (RLVa 2.2.0)

NorthernCollar V8.0 (Chest):
  -> setgroup

**Pull request merged**
