### PR TITLE
Various fixes to oc_api and oc_core

### PR DESCRIPTION
**Pull request by Medea-Destiny**
oc_api:                 *Fix issue #566  setgroup not clearing properly, 
                            *Fix issue #562, #381, #495 allow owners to permit wearers to set trusted/block
                            *Fix issue #579 Add interface channel to DoListeners() function so Highlander works again
                            *Issue #579 Restored menuto function to interface channel for backwards compatibility
                            *Issue #579 Added control of channel 0 listening via settings menu
                            *Fix issue 585 give wearer accept/deny dialog to confirm runaway disable setting
oc_core:               *Fix issue #562, #381, #495 allow owners to permit wearers to set trusted/block.
                            -   added Wearer Trust option to Access Menu so that owners may allow or forbid
                                wearer from adding/removing to trusted and block lists
                            -   Moved Limit Range to Settings menu to make room in Access menu for above,
                                as it seems logical to have this as a global setting. 
                            *Added explanatory text to settings menu prompt and access prompt,
                            *Added safeword to help/about prompt. 
                            *Fix issue #566, clear @setgroup when group unchecked properly.
                            *Extention to above, Disallow setting group access when no group active.  
                            *Fix issue #580 Limited printing settings to owner and wearer
                            *#579 Added 'Listen 0' button to Settings menu that allows toggling channel 0 command listener on and off.  

These are issues as a single pull due to the interdependency of various functions of these scripts. Testing should be done with BOTH oc_api and oc_core at the same time.

### CODE REVIEW

**Review by Pingout — COMMENTED** [review]
When I swap this script into the 8.0.5 collar I can not add an owner or trusted to my access. I get a sub menu when I try but the only option in the sub menu is to add >Wearer<
When both new oc_core and oc_api are in the collar, I get nothing when I try to add an owner or trusted. As Trinkitz says, the menu poofs

**Comment by Trinkitz** [comment]
I cannot add an Owner, Trusted or Block with this new script. I tested everything I could, but until access is fixed, I cannot go any further with testing. Thank you.

**Comment by Medea-Destiny** [comment]
That should fix the issue, I had a comparison check happening inside another comparison check that contradicted it. I will never be persuaded that K&R indentation style is a good idea - white space is free, readability is not. :P

**Comment by Trinkitz** [comment]
We made a lot of progress today; forwarding findings to Ping. We still have some work to do, but so far this looks very good.

**Review by SilkieSabra — APPROVED** [review]
All of this looks good to me, thanks to our testing team! One wrinkle, I don't know git that well and this is asking to merge into master, it needs to go into https://github.com/OpenCollarTeam/OpenCollar/tree/features-2021-q2 instead.  I'm guessing it works if you are in the features branch when making the fix? I can't see how to merge into the correct branch on this pull.

**Comment by Medea-Destiny** [comment]
USE #593 rather than this pull request!

I have no idea why this now wants to merge tayaphidoux's work on the AO stuff, this is possibly because I shifted to the features base from the master base and there's stuff that got merged with master rather than features and something got out of sync, but this ain't my stuff and I have no idea what the correct versions are so best to avoid.

**Pull request closed without merging**
