### PR TITLE
Update oc_unwelder.lsl

### PR DESCRIPTION
**Pull request by Medea-Destiny**
Fix for #859

### CODE REVIEW

**Comment by Medea-Destiny** [comment]
Okay. So I think this should do it. To test:
Wearer with trusted permission can now unweld as normal.
Owner of unwelder cannot unweld collars they do not have permissions for (i.e not wearer or owner).
Both unwelder and unwelder HUD are working as intended.

**Comment by Pingout** [comment]
Omnia and I tested this: 
1. Wearer with trusted permission can now unweld as normal.
2. The second test is not valid: There's no way for someone who is not the collar wearer to unweld a collar
3. Both unwelder and unwelder HUD are working as intended.
Thank you for the fix!

**Comment by SilkieSabra** [comment]
I'm being a stickler here for checking that Approved box.

**Review by Pingout — APPROVED** [review]
Approved as noted above.

**Review by Pingout — APPROVED** [review]
Approved as noted above.

**Pull request merged**
