### PR TITLE
Request for removal of virtualdisgrace.com branded textures

### PR DESCRIPTION
**Pull request by WendyStarfall**
On behalf of virtualdisgrace.com, I am requesting the removal of our GUI button textures, and their corresponding asset identifiers of the textures that were uploaded to the Second Life® Agni virtual world grid.

The textures are my original creations. I have made them for the Remote and Animation Overrider HUD interfaces of my own, and of virtualdisgrace.com branded distributions of the OpenCollar Role Play Device.

The material in question is listed as "removed binary files", and as "deletions", in the commits that are attached to this pull request. The originals can be found in my own git repository at https://github.com/WendyStarfall/opencollar/tree/master/res/textures

Based on a commit d1ed7c48c158fa0a9e112c2d55bc81c8b48041c3 where virtualdisgrace.com branding and web links are removed and altered, and defamation and brand disparagement as seen [here](https://github.com/OpenCollarTeam/OpenCollar/blob/master/notecards/2017-11-21-What_the_opencollar_name_stands_for.md#openness-and-fairness), I have a good faith belief that the use of our GUI button textures is not authorized by the copyright owner, its agent, or by law.

All the information above is accurate.

Wendy Starfall
for virtualdisgrace.com

### CODE REVIEW

**Comment by WendyStarfall** [comment]
#80 #81

**Comment by GarvinTwine** [comment]
It's kinda wrong to call the AO script, I made under virtualdisgrace.com, for opencollar simply to be "part of opencollar" and removing all traces of it's origin from virtualdisgrace.com.
The oc_ao script would not exist at all if not done under the virtualdisgrace.com, branding.
Same applies to the oc_remote_sys script which got created the same way, though it might have more traces of other opencollar scripts than oc_ao in it.
Both times we always credited everyone even if it was just one line of code.
Sad to see how it goes very different the other way around, where our work gets blamed when ever possible (or just not understood) though still used.

**Comment by nirea** [comment]
To make sure I understand, are you no longer offering these textures under the Creative Commons Attribution-ShareAlike license, as indicated at https://github.com/VirtualDisgrace/opencollar/blob/master/LICENSE?

https://creativecommons.org/faq/#what-happens-if-the-author-decides-to-revoke-the-cc-license-to-material-i-am-using

**Comment by Saraeva** [comment]
@nirea as the title says, "**Request** for removal of virtualdisgrace.com branded textures". Please comply.

**Comment by nirea** [comment]
Few of the textures referenced in this pull request have VD branding, though.

And the position's expressed by VD team members in this thread are pulling both ways.  Wendy wants textures removed for including VD branding, while Garvin is upset that certain scripts *don't* have VD branding.

As far as branding goes, I actually agree with Wendy.  We can make sure that OpenCollar does not include any VirtualDisgrace branding.  It's important to me to avoid user confusion, and I've done quite a lot of work towards that already.  It would be a show of good faith if VirtualDisgrace would also stop using OpenCollar branding.

**Comment by Saraeva** [comment]
@nirea you're straying from the issue at hand, which is the request for the removal of virtualdisgrace.com branded textures. Please comply.

**Comment by nirea** [comment]
We're discussing precisely the issue at hand, @Saraeva, whether these textures should be removed from the repository.

If @WendyStarfall would like to re-submit the pull request to remove just the textures with the VD dripping heart logo on them (I know of two in the remote) that would make sense.  I don't see how the rest are VirtualDisgrace branded.

**Comment by nirea** [comment]
d2af49a23463e27cc9fba0a95e2d4606efd44f91 makes this request moot.  We're going a different direction with the remote hud, and with the AO soon.  Same result as far as this pull request is concerned though.

**Comment by WendyStarfall** [comment]
Thank you.

**Comment by kyrahabattoir** [comment]
I like how because it's @WendyStarfall asking, suddently you feel like resisting @nirea.

**Pull request closed without merging**
