### PR TITLE
Update oc_rlvextension.lsl

### PR DESCRIPTION
**Pull request by Medea-Destiny**
Fix for issue #703

### CODE REVIEW

**Review by nightshade231 — COMMENTED** [review]
tessting this currently.-

**Review by 1Acadia — COMMENTED** [review]
Script was tested with my sub and also my alt. The Force Sit and Unsit worked as expected. I then repeated the test using the Remote.  Again both functions worked properly.

**Comment by SilkieSabra** [comment]
This one is ready to merge if only one of these reviewers had submitted an Approving review.  It seems they did approve based on the comments.

**Comment by Omnia2021** [comment]
This aspect works as intended see no issues with use or performance.

**Review by Omnia2021 — APPROVED** [review]
Everything works as intended no issues were observed in testing over a long duration.

**Comment by SilkieSabra** [comment]
I'm going to go ahead and merge this.  We've waited a very long time for a coder willing to step forward and proclaim that this simple bug fix meets the OC style standard and doesn't break anything.

**Review by LisleRossini — APPROVED** [review]
[CODE REVIEW] I have reviewed the changes and see no obvious errors or breaches of the style guide.

**Pull request merged**
