### PR TITLE
code style formatting

### PR DESCRIPTION
**Pull request by riej**
automatically reformatted using JetBrains plugin

### CODE REVIEW

**Comment by SilkieSabra** [comment]
riej, hello ! purpose of the reformatting, was it reformatted to conform to the OC style guide? and, please make prs to the 8.3 features branch so the master branch does not get ahead of the next version.

**Comment by riej** [comment]
The purpose is to make source code to be better to read. I close this PR and will make new one, to the 8.3 branch.

**Comment by SilkieSabra** [comment]
Have you consulted the style guide?

**Comment by SilkieSabra** [comment]
Thanks again, according to our https://opencollar.cc/docs/Development-Life-Cycle your next step will be to compile the scripts you edited inworld, preferably in the form of an updater, so it can be tested for review.

**Comment by riej** [comment]
*sighs* Ok, will do it in next couple days. Whom should I send it in SL (username)?

https://github.com/OpenCollarTeam/OpenCollar/pull/968 - new PR, btw.

**Comment by SilkieSabra** [comment]
Thanks, yes it's a lot of work, this will make it much easier for the testers.  Send it to me, roan secondlife:///app/agent/1a828b4e-6345-4bb3-8d41-f93e6621ba25/inspect

**Pull request closed without merging**
