### PR TITLE
Update oc_api.lsl

### PR DESCRIPTION
**Pull request by Medea-Destiny**
Fixes for #774 , #847, #843 , #849

### CODE REVIEW

**Comment by Medea-Destiny** [comment]
Testing required:

1. Compatibility of interface channel (try adding a second copy of the collar and checking the collar detaches, both with another 8.2.2 and earlier collar versions.
2. Wearer who is trusted access to runaway functionality
3. Wearer who is trusted access to adding trusted with wearertrust active
4. Other potential conflicts with wearer who is trusted.

**Comment by Medea-Destiny** [comment]
Added a new fix: (prefix)prefix reset was not working as advertised in instructions. I have added the functionality and added notification to the menu user and wearer of a new prefix when changed.

**Comment by Pingout** [comment]
Tested by Ping and Omnia:

Wearer who is trusted access to adding trusted with wearertrust active <-- this is not true. 
The note in the Access menu says "Wearer trust allows an owned wearer to add/remove from trusted list." <-- this is true
if the wearer is owned they can add trusted, but if they are owned and trusted they can not add a trusted

**Comment by Medea-Destiny** [comment]
The problem @Pingout and Omnia observed was not actually to do with this script, but oc_core.

To clarify -- this script handles actually adding people to lists, however the menu is served from the oc_core scripts. There are fixes in the oc_core script that handle that side of things, and thus this PR needs to be tested on top of the current beta, not with the 8.2.1 version of oc_core.

Ping has confirmed that with both oc_api and oc_core updated, the trusted adding is working with both menu and chat commands.

**Comment by Pingout** [comment]
@SilkieSabra this PR can be merged

**Comment by SilkieSabra** [comment]
@Pingout if you say it can be merged can you please tick the Approved box?

**Pull request merged**
