### PR TITLE
Fixes the anti slide and animation playback

### PR DESCRIPTION
**Pull request by zontreck**
Fixes the animation overriders so that the anti slide works. Switches animation playback to animation override

### CODE REVIEW

**Comment by Medea-Destiny** [comment]
I don't believe this is the right approach, at least as it currently stands. Using llSetAnimationOverride here will conflict with llSetAnimationOverride AOs. We might consider direct integration with OCAO as way to handle this, with a message sent on llResetAnimationOverride to the AO to restore stand overrides, but even then this should be an optional switch for people who use non-compatible animation overriding devices. 

The posture animations should not be a stand override, as that will replace any existing stand animation. Posture animation should be a pri 5/6 neck-only animation which will play on top of existing stand and pose animations.

**Comment by zontreck** [comment]
Perfectly fine. Just wanted to attempt to fix it is all.

**Comment by zontreck** [comment]
I do ask however that you do try the fix as it does actually work. So until you do integrate with OCAO, this works perfectly fine.

**Comment by zontreck** [comment]
Also on a side now- I do not even use the OCAO, so if you plan on moving all animation playback to that, then that will cut off my and probably- many users' abilities to use the OC animations as that will conflict with their existing AOs.

I'd RATHER Fix the existing implementation rather than making everyone's lives more difficult with weighting down with additional scripts. Just food for thought alright?

I personally roleplay on sims that cutoff the script count at around a hundred scripts per avatar. The collar alone adds plenty, but adding an AO HUD as a requirement to that mix takes up two things, a attachment point and additional script(s). So please consider this before making this change as not everyone will be pleased with it.

**Comment by zontreck** [comment]
--As this conflicts with lSetAnimationOverride AOs, i am closing this pullrequest until i or someone else comes up with a better solution.

**Pull request closed without merging**
