### PR TITLE
OC_AO 2.0dev1 ready

### PR DESCRIPTION
**Pull request by KristenMynx**
Per #80 Create OpenCollar AO Linkset (in res/models)
A few version related changes

### CODE REVIEW

**Comment by KristenMynx** [comment]
Sure I can do that.... I did this work before I saw the other changes.

**Comment by KristenMynx** [comment]
@nirea Did you want one sprite sheet to be used with both the remote and ao devices?   If not I'll cobble together another sheet with the buttons that are needed.

If you do want one sheet, we need minimize/maximize (covered in your sheet with + and -), power, ground sit, and menu (the current menu is 3lines,  would reuse of settings be proper?)

**Comment by nirea** [comment]
I made a sprite sheet with just those buttons and uploaded to
https://i.imgur.com/XU1lBCD.png.

**Comment by KristenMynx** [comment]
Buttons redone in additional commit https://github.com/OpenCollarTeam/OpenCollar/pull/87/commits/acd1f75f3637a6316ef9a549965a20b1f67b7636, tested, ready to merge.

**Pull request merged**
