### PR TITLE
Sound normalization

### PR DESCRIPTION
**Pull request by Trix7125**
Fix the bell sounds that you can actually hear something.

### CODE REVIEW

**Review by Pingout — APPROVED** [review]
I tested this inworld and found the sounds much improved. Where previously you could barely hear many of the bell sounds, you can now hear all of them clearly, and even be able to adjust the volume down and still hear the sound. Thank you!

**Comment by Pingout** [comment]
Oh and I moved the PR so that it now points at the 8.3 Features Branch

**Review by Medea-Destiny — CHANGES_REQUESTED** [review]
Code change is just a change of the sound list, zero problems there.

@Trix7125 can you add an update line to the comments at the top to show your revision, in along the lines:

Trix (SL name in brackets if you want):
    27 feb 2024: Updated bell sounds to normalise volume, and replaced g_listBellSounds with new values.

Also we don't really need the old values commented out, please delete those.

Nice work! Thanks very much.

**Comment by Trix7125** [comment]
I removed the old list and added commend top of file.

**Review by Pingout — APPROVED** [review]
Approved as edited. We still need to point all Pull Requests at the 8.3 Features Branch of the repository until such time as we are ready to Upgrade to the next Version.
Thank you!

**Review by Medea-Destiny — APPROVED** [review]
@Trix7125 
Thanks for the changes! All good now.

**Pull request merged**
