### PR TITLE
Update oc_rlvextension.lsl

### PR DESCRIPTION
**Pull request by Medea-Destiny**
Fix for issues #844 & #848

### CODE REVIEW

**Comment by Medea-Destiny** [comment]
Testing required:
Ensure that only Owners can change the exceptions list.

**Comment by Pingout** [comment]
Tested by Ping and Omnia:

Ping is Owner in Rio's collar, Omnia is Trusted in that same collar
Both of us are able to change the Exceptions list for both Owner and Trusted
The changes Omnia makes are changing both Owner and Trusted exceptions, but according to the script she should be blocked from changing exceptions

I think the script fix is not working yet

**Comment by Medea-Destiny** [comment]
@Pingout When you go into the exceptions menu (the one with buttons for Owner, Trusted, Custom and BACK) anyone without owner permission should see the message "No access to changing exceptions!" and be kicked back up a menu level to the RLV menu when clicking on any button other than the BACK button. Can you clarify what the point of failure is please?

**Comment by Pingout** [comment]
> @Pingout When you go into the exceptions menu (the one with buttons for Owner, Trusted, Custom and BACK) anyone without owner permission should see the message "No access to changing exceptions!" and be kicked back up a menu level to the RLV menu when clicking on any button other than the BACK button. Can you clarify what the point of failure is please?

Oki, so here's what happened. Before the test I copied the new script into the test collar, and then, thinking i needed the rest of the updated files I ran the 8.2.2.010 Beta Updater. Which over-wrote the new rlvextentions with the older one.

Once we had the correct script in the collar, the script worked as it's supposed to, blocking Trusted, or any non-owner, from accessing the Exceptions list. Test successful.

@SilkieSabra  this PR can be merged.

**Comment by SilkieSabra** [comment]
@Pingout if you say it can be merged, contribute the approving review to that effect.

**Review by Pingout — APPROVED** [review]
Approved as noted above. Thanks Medea!

**Pull request merged**
